import media
import fresh_tomatoes

national_treasure = media.Movie ("National Treasure","Cage plays Benjamin Franklin Gates, a historian and amateur cryptologist searching for a lost treasure of precious metals, jewelry, artwork and other artifacts that was accumulated into a single massive stockpile by looters and warriors over many millennia starting in Ancient Egypt, later rediscovered by warriors who form themselves into the Knights Templar to protect the treasure, eventually hidden by American Freemasons during the American Revolutionary War.", "http://upload.wikimedia.org/wikipedia/en/1/12/Movie_national_treasure.JPG","https://www.youtube.com/watch?v=mcf4tXYjaxo" , 2000)

kings_speech = media.Movie ("The King's Speech", "Cage plays Benjamin Franklin Gates, a historian and amateur cryptologist searching for a lost treasure of precious metals, jewelry, artwork and other artifacts that was accumulated into a single massive stockpile by looters and warriors over many millennia starting in Ancient Egypt, later rediscovered by warriors who form themselves into the Knights Templar to protect the treasure, eventually hidden by American Freemasons during the American Revolutionary War.", "http://upload.wikimedia.org/wikipedia/en/1/12/Movie_national_treasure.JPG","https://www.youtube.com/watch?v=mcf4tXYjaxo" , 2000)

the_judge = media.Movie ("The Judge", "Cage plays Benjamin Franklin Gates, a historian and amateur cryptologist searching for a lost treasure of precious metals, jewelry, artwork and other artifacts that was accumulated into a single massive stockpile by looters and warriors over many millennia starting in Ancient Egypt, later rediscovered by warriors who form themselves into the Knights Templar to protect the treasure, eventually hidden by American Freemasons during the American Revolutionary War.", "http://en.wikipedia.org/wiki/National_Treasure_%28film%29#/media/File:Movie_national_treasure.JPG","https://www.youtube.com/watch?v=mcf4tXYjaxo" , 2000)

imitation_game = media.Movie ("Imitation Game", "Cage plays Benjamin Franklin Gates, a historian and amateur cryptologist searching for a lost treasure of precious metals, jewelry, artwork and other artifacts that was accumulated into a single massive stockpile by looters and warriors over many millennia starting in Ancient Egypt, later rediscovered by warriors who form themselves into the Knights Templar to protect the treasure, eventually hidden by American Freemasons during the American Revolutionary War.", "http://en.wikipedia.org/wiki/National_Treasure_%28film%29#/media/File:Movie_national_treasure.JPG","https://www.youtube.com/watch?v=mcf4tXYjaxo", 2000)

twenty_one = media.Movie ("Twenty One", "Cage plays Benjamin Franklin Gates, a historian and amateur cryptologist searching for a lost treasure of precious metals, jewelry, artwork and other artifacts that was accumulated into a single massive stockpile by looters and warriors over many millennia starting in Ancient Egypt, later rediscovered by warriors who form themselves into the Knights Templar to protect the treasure, eventually hidden by American Freemasons during the American Revolutionary War.", "http://en.wikipedia.org/wiki/National_Treasure_%28film%29#/media/File:Movie_national_treasure.JPG","https://www.youtube.com/watch?v=mcf4tXYjaxo", 2000)


movies = [national_treasure , kings_speech , the_judge , imitation_game , twenty_one]
fresh_tomatoes.open_movies_page(movies);
